# Generated by Django 5.0.4 on 2024-06-01 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_screen_alter_screenpermissions_screen_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screenpermissions',
            name='screen_name',
            field=models.CharField(blank=True, choices=[('admin_screen', 'Admin Management'), ('review_screen', 'Review Management'), ('venue_screen', 'Venue Management'), ('attendance_screen', 'Attendance Management'), ('news_screen', 'News Management'), ('notification_screen', 'Notification Management')], max_length=255, null=True),
        ),
    ]
