# Generated by Django 5.0.4 on 2024-06-01 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_screenpermissions_screen_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screenpermissions',
            name='screen_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='authentication.screen'),
        ),
    ]
