# Generated by Django 5.0.4 on 2024-06-01 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_screenpermissions_screen_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='screen',
            options={'verbose_name': '前端頁面', 'verbose_name_plural': '前端頁面'},
        ),
        migrations.AlterModelOptions(
            name='screenpermissions',
            options={'verbose_name': '前端頁面權限', 'verbose_name_plural': '前端頁面權限'},
        ),
        migrations.AlterModelTable(
            name='screen',
            table='screen',
        ),
        migrations.AlterModelTable(
            name='screenpermissions',
            table='screen_permissions',
        ),
    ]
