# Generated by Django 5.0.4 on 2024-06-01 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_screen_options_alter_screenpermissions_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screenpermissions',
            name='screen_name',
            field=models.CharField(blank=True, choices=[('admin_screen', 'Admin Management'), ('review_screen', 'Review Management'), ('venue_screen', 'Venue Management'), ('attendance_screen', 'Attendance Management'), ('news_screen', 'News Management'), ('notification_screen', 'Notification Management')], max_length=255, null=True),
        ),
        migrations.AlterModelOptions(
            name='screenpermissions',
            options={},
        ),
        migrations.AlterModelTable(
            name='screenpermissions',
            table=None,
        ),
        migrations.DeleteModel(
            name='Screen',
        ),
    ]
