# Generated by Django 5.0.4 on 2024-06-01 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_screenpermissions_screen_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screenpermissions',
            name='screen_name',
            field=models.CharField(blank=True, choices=[('admin_screen', 'Admin Management'), ('review_screen', 'Review Management'), ('venue_screen', 'Venue Management'), ('attendance_screen', 'Attendance Management'), ('news_screen', 'News Management'), ('notification_screen', 'Notification Management'), ('worklog_screen', 'Worklog Management'), ('repair_screen', 'Repair Management')], max_length=255, null=True),
        ),
    ]
