# Generated by Django 5.0.4 on 2024-06-01 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_alter_screenpermissions_screen_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='screenpermissions',
            options={'verbose_name': '頁面渲染權限', 'verbose_name_plural': '頁面渲染權限'},
        ),
        migrations.AlterField(
            model_name='screenpermissions',
            name='screen_name',
            field=models.CharField(blank=True, choices=[('admin_screen', 'Admin Management'), ('review_screen', 'Review Management'), ('venue_screen', 'Venue Management'), ('attendance_screen', 'Attendance Management'), ('news_screen', 'News Management'), ('notification_screen', 'Notification Management'), ('worklog_screen', 'Worklog Management'), ('Repair Management', 'repair_screen'), ('Check Management', 'checkin_screen')], max_length=255, null=True),
        ),
        migrations.AlterModelTable(
            name='screenpermissions',
            table='ScreenPermissions',
        ),
    ]
