# Generated by Django 5.0.4 on 2024-06-01 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_alter_screenpermissions_screen_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('screen_name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': '頁面',
                'verbose_name_plural': '頁面',
                'db_table': 'Screen',
            },
        ),
        migrations.AlterField(
            model_name='screenpermissions',
            name='screen_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.screen'),
        ),
    ]
