# Generated by Django 5.0.4 on 2024-06-02 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_screen_alter_screenpermissions_screen_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screen',
            name='name',
        ),
    ]
