# Generated by Django 5.0.4 on 2024-06-02 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_remove_screen_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='nickname',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='暱稱'),
        ),
    ]
