# Generated by Django 5.0.4 on 2024-05-18 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VenueBookingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待審核'), ('reviewing', '審核中'), ('approved', '已批准'), ('rejected', '已拒絕'), ('requires_more_info', '需要更多信息'), ('cancelled', '已取消'), ('on_hold', '暫停'), ('re_review', '重新審核'), ('auto_approved', '自動批准'), ('expired', '已過期')], default='pending', max_length=20)),
                ('name', models.CharField(max_length=255, verbose_name='狀態名稱')),
                ('description', models.TextField(verbose_name='狀態描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '場地預約狀態',
                'verbose_name_plural': '場地預約狀態',
                'db_table': 'venue_booking_status',
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待審核'), ('reviewing', '審核中'), ('approved', '已批准'), ('rejected', '已拒絕'), ('requires_more_info', '需要更多信息'), ('cancelled', '已取消'), ('on_hold', '暫停'), ('re_review', '重新審核'), ('auto_approved', '自動批准'), ('expired', '已過期')], default='pending', max_length=20)),
                ('name', models.CharField(max_length=255, verbose_name='場地名稱')),
                ('description', models.TextField(verbose_name='場地描述')),
                ('capacity', models.IntegerField(verbose_name='容量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('weekday_open_time', models.TimeField(blank=True, null=True, verbose_name='平日開放時間')),
                ('weekday_close_time', models.TimeField(blank=True, null=True, verbose_name='平日關閉時間')),
                ('holiday_open_time', models.TimeField(blank=True, null=True, verbose_name='假日開放時間')),
                ('holiday_close_time', models.TimeField(blank=True, null=True, verbose_name='假日關閉時間')),
                ('longitude', models.FloatField(default=0, verbose_name='經度')),
                ('latitude', models.FloatField(default=0, verbose_name='緯度')),
                ('address', models.CharField(default='', max_length=255, verbose_name='地址')),
                ('managers', models.ManyToManyField(related_name='venues', to=settings.AUTH_USER_MODEL, verbose_name='場地管理者')),
            ],
            options={
                'verbose_name': '場地',
                'verbose_name_plural': '場地',
                'db_table': 'venue',
            },
        ),
        migrations.CreateModel(
            name='VenueBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待審核'), ('reviewing', '審核中'), ('approved', '已批准'), ('rejected', '已拒絕'), ('requires_more_info', '需要更多信息'), ('cancelled', '已取消'), ('on_hold', '暫停'), ('re_review', '重新審核'), ('auto_approved', '自動批准'), ('expired', '已過期')], default='pending', max_length=20)),
                ('start_time', models.DateTimeField(verbose_name='開始時間')),
                ('end_time', models.DateTimeField(verbose_name='結束時間')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venue_bookings', to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venue_bookings', to='venues.venue', verbose_name='場地')),
            ],
            options={
                'verbose_name': '場地預約',
                'verbose_name_plural': '場地預約',
                'db_table': 'venue_booking',
            },
        ),
        migrations.CreateModel(
            name='VenueInspectionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待審核'), ('reviewing', '審核中'), ('approved', '已批准'), ('rejected', '已拒絕'), ('requires_more_info', '需要更多信息'), ('cancelled', '已取消'), ('on_hold', '暫停'), ('re_review', '重新審核'), ('auto_approved', '自動批准'), ('expired', '已過期')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venue_inspection_records', to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venue_inspection_records', to='venues.venue', verbose_name='場地')),
            ],
            options={
                'verbose_name': '巡檢紀錄',
                'verbose_name_plural': '巡檢紀錄',
                'db_table': 'venue_inspection_record',
            },
        ),
        migrations.CreateModel(
            name='VenueRepairRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待審核'), ('reviewing', '審核中'), ('approved', '已批准'), ('rejected', '已拒絕'), ('requires_more_info', '需要更多信息'), ('cancelled', '已取消'), ('on_hold', '暫停'), ('re_review', '重新審核'), ('auto_approved', '自動批准'), ('expired', '已過期')], default='pending', max_length=20)),
                ('repair_status', models.CharField(choices=[('not_processed', '未處理'), ('processing', '處理中'), ('processed', '已處理')], default='not_processed', max_length=20, verbose_name='報修狀態')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='報修標題')),
                ('description', models.TextField(verbose_name='報修描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venue_repair_requests', to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venue_repair_requests', to='venues.venue', verbose_name='場地')),
            ],
            options={
                'verbose_name': '報修申請',
                'verbose_name_plural': '報修申請',
                'db_table': 'venue_repair_request',
            },
        ),
        migrations.CreateModel(
            name='VenueUsageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待審核'), ('reviewing', '審核中'), ('approved', '已批准'), ('rejected', '已拒絕'), ('requires_more_info', '需要更多信息'), ('cancelled', '已取消'), ('on_hold', '暫停'), ('re_review', '重新審核'), ('auto_approved', '自動批准'), ('expired', '已過期')], default='pending', max_length=20)),
                ('venue_status', models.CharField(choices=[('not_used', '未使用'), ('booked', '已預訂'), ('in_use', '使用中'), ('repairing', '維修中'), ('closed', '已關閉')], default='not_used', max_length=20, verbose_name='場地狀態')),
                ('start_time', models.DateTimeField(verbose_name='開始時間')),
                ('end_time', models.DateTimeField(verbose_name='結束時間')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='venue_usage_records', to='courses.course', verbose_name='課程')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venue_usage_records', to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venue_usage_records', to='venues.venue', verbose_name='場地')),
            ],
            options={
                'verbose_name': '場地使用紀錄',
                'verbose_name_plural': '場地使用紀錄',
                'db_table': 'venue_usage_record',
            },
        ),
    ]
