# Generated by Django 5.0.4 on 2024-05-26 11:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='managers',
            field=models.ManyToManyField(blank=True, null=True, related_name='venues', to=settings.AUTH_USER_MODEL, verbose_name='場地管理者'),
        ),
    ]
