# Generated by Django 5.0.4 on 2024-05-26 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0002_alter_venue_address_alter_venue_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='場地描述'),
        ),
    ]
