# Generated by Django 5.0.4 on 2024-06-01 15:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0004_alter_venue_managers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='managers',
            field=models.ManyToManyField(blank=True, related_name='venues', to=settings.AUTH_USER_MODEL, verbose_name='場地管理者'),
        ),
    ]
