# Generated by Django 5.0.8 on 2024-08-13 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0011_alter_venue_status_alter_venuebooking_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VenueManagerList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False, verbose_name='是否為主要管理者')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_venues', to=settings.AUTH_USER_MODEL, verbose_name='管理者')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venue_managers', to='venues.venue', verbose_name='場地')),
            ],
            options={
                'verbose_name': '場地管理者',
                'verbose_name_plural': '場地管理者',
                'db_table': 'venue_manager_list',
                'unique_together': {('venue', 'user')},
            },
        ),
    ]
