# Generated by Django 5.0.4 on 2024-05-26 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worklog', '0003_remove_specialcheckrecord_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worklog',
            name='is_final',
            field=models.BooleanField(default=False),
        ),
    ]
