# Generated by Django 5.0.4 on 2024-07-17 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worklog', '0010_dailycheckrecord_date_dailycheckrecord_venue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worklog',
            name='daily_checks',
        ),
        migrations.RemoveField(
            model_name='worklog',
            name='periodic_checks',
        ),
        migrations.RemoveField(
            model_name='worklog',
            name='special_checks',
        ),
        migrations.AddField(
            model_name='worklog',
            name='daily_checks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='worklog.dailycheckrecord'),
        ),
        migrations.AddField(
            model_name='worklog',
            name='periodic_checks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='worklog.periodiccheckrecord'),
        ),
        migrations.AddField(
            model_name='worklog',
            name='special_checks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='worklog.specialcheckrecord'),
        ),
    ]
