# Generated by Django 5.0.4 on 2024-07-17 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worklog', '0011_remove_worklog_daily_checks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailycheckrecord',
            name='duty',
        ),
        migrations.RemoveField(
            model_name='periodiccheckrecord',
            name='duty',
        ),
        migrations.RemoveField(
            model_name='specialcheckrecord',
            name='duty',
        ),
        migrations.RemoveField(
            model_name='worklog',
            name='content',
        ),
        migrations.RemoveField(
            model_name='worklog',
            name='daily_checks',
        ),
        migrations.RemoveField(
            model_name='worklog',
            name='periodic_checks',
        ),
        migrations.RemoveField(
            model_name='worklog',
            name='special_checks',
        ),
        migrations.RemoveField(
            model_name='worklog',
            name='title',
        ),
        migrations.AddField(
            model_name='dailycheckrecord',
            name='worklog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='worklog.worklog', verbose_name='工作日誌'),
        ),
        migrations.AddField(
            model_name='periodiccheckrecord',
            name='Worklog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='worklog.worklog', verbose_name='工作日誌'),
        ),
        migrations.AddField(
            model_name='specialcheckrecord',
            name='worklog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='worklog.worklog', verbose_name='工作日誌'),
        ),
        migrations.AddField(
            model_name='worklog',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='描述'),
        ),
    ]
