# Generated by Django 5.0.4 on 2024-07-17 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worklog', '0012_remove_dailycheckrecord_duty_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='periodiccheckrecord',
            old_name='Worklog',
            new_name='worklog',
        ),
    ]
