# Generated by Django 5.0.4 on 2024-07-17 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worklog', '0013_rename_worklog_periodiccheckrecord_worklog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailycheckrecord',
            name='venue',
        ),
    ]
