# Generated by Django 5.0.4 on 2024-07-28 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worklog', '0014_remove_dailycheckrecord_venue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailycheckrecord',
            name='score',
            field=models.CharField(blank=True, choices=[('優', '優'), ('尚可', '尚可'), ('需改善', '需改善')], default='優', max_length=20, null=True, verbose_name='評分'),
        ),
    ]
