# Generated by Django 5.0.4 on 2024-07-28 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worklog', '0015_alter_dailycheckrecord_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailycheckrecord',
            name='date',
        ),
    ]
