# Generated by Django 5.0.4 on 2024-07-28 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worklog', '0016_remove_dailycheckrecord_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailycheckrecord',
            name='status',
        ),
    ]
