# Generated by Django 5.0.4 on 2024-07-28 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0010_lifeguardschedule_schedule_status_and_more'),
        ('worklog', '0017_remove_dailycheckrecord_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailycheckrecord',
            name='worklog',
        ),
        migrations.RemoveField(
            model_name='periodiccheckrecord',
            name='worklog',
        ),
        migrations.RemoveField(
            model_name='specialcheckrecord',
            name='worklog',
        ),
        migrations.AddField(
            model_name='dailycheckrecord',
            name='duty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.lifeguardschedule', verbose_name='值班人員'),
        ),
        migrations.AddField(
            model_name='periodiccheckrecord',
            name='duty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.lifeguardschedule', verbose_name='值班人員'),
        ),
        migrations.AddField(
            model_name='specialcheckrecord',
            name='duty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.lifeguardschedule', verbose_name='值班人員'),
        ),
        migrations.AlterField(
            model_name='dailycheckrecord',
            name='score',
            field=models.CharField(blank=True, choices=[('優良', '優良'), ('尚可', '尚可'), ('需改善', '需改善')], default='優', max_length=20, null=True, verbose_name='評分'),
        ),
    ]
