# Generated by Django 5.0.4 on 2024-07-29 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worklog', '0018_remove_dailycheckrecord_worklog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodiccheckrecord',
            name='value',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='數值'),
        ),
        migrations.AlterField(
            model_name='specialcheckrecord',
            name='quantity',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='數量'),
        ),
    ]
