# Generated by Django 5.0.4 on 2024-07-29 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worklog', '0019_alter_periodiccheckrecord_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialcheckrecord',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='結束時間'),
        ),
        migrations.AlterField(
            model_name='specialcheckrecord',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='開始時間'),
        ),
    ]
