# Generated by Django 5.0.4 on 2024-05-26 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_remove_coursetype_capacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollmentlist',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='開始上課日期'),
        ),
        migrations.AlterField(
            model_name='enrollmentlist',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='上課時間'),
        ),
    ]
