# Generated by Django 5.0.4 on 2024-05-26 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_enrollmentlist_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollmentlist',
            name='enrollment_status',
            field=models.CharField(blank=True, choices=[('pending_payment', '待付款'), ('in_progress', '審核中'), ('in_assigned', '派課中'), ('assigned', '已派課'), ('completed', '已完成'), ('cancelled', '已取消'), ('refunded', '已退款')], max_length=20, null=True, verbose_name='報名狀態'),
        ),
    ]
