# Generated by Django 5.0.4 on 2024-05-26 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_remove_enrollmentnumbers_coach_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollmentnumbers',
            name='enrollments',
            field=models.ManyToManyField(blank=True, related_name='enrollment_numbers', to='courses.enrollmentlist', verbose_name='報名單編號'),
        ),
    ]
