# Generated by Django 5.0.4 on 2024-06-06 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_assignedcourse_status_alter_course_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedcourse',
            name='status',
            field=models.CharField(choices=[('pending', '待審核'), ('reviewing', '審核中'), ('approved', '已批准'), ('rejected', '已拒絕'), ('requires_more_info', '需要更多信息'), ('cancelled', '已取消'), ('on_hold', '暫停'), ('re_review', '重新審核'), ('auto_approved', '自動批准'), ('expired', '已過期')], default='pending', max_length=20, verbose_name='審核狀態'),
        ),
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('pending', '待審核'), ('reviewing', '審核中'), ('approved', '已批准'), ('rejected', '已拒絕'), ('requires_more_info', '需要更多信息'), ('cancelled', '已取消'), ('on_hold', '暫停'), ('re_review', '重新審核'), ('auto_approved', '自動批准'), ('expired', '已過期')], default='pending', max_length=20, verbose_name='審核狀態'),
        ),
        migrations.AlterField(
            model_name='coursetype',
            name='status',
            field=models.CharField(choices=[('pending', '待審核'), ('reviewing', '審核中'), ('approved', '已批准'), ('rejected', '已拒絕'), ('requires_more_info', '需要更多信息'), ('cancelled', '已取消'), ('on_hold', '暫停'), ('re_review', '重新審核'), ('auto_approved', '自動批准'), ('expired', '已過期')], default='pending', max_length=20, verbose_name='審核狀態'),
        ),
        migrations.AlterField(
            model_name='enrollmentlist',
            name='enrollment_status',
            field=models.CharField(blank=True, choices=[('pending_payment', '待付款'), ('not_started', '未開課'), ('in_reviews', '審核中'), ('in_assigned', '派課中'), ('assigned', '已派課'), ('in_progress', '進行中'), ('completed', '已完成'), ('cancelled', '已取消'), ('refunded', '已退款'), ('suspended', '已停課')], max_length=20, null=True, verbose_name='報名狀態'),
        ),
        migrations.AlterField(
            model_name='enrollmentlist',
            name='status',
            field=models.CharField(choices=[('pending', '待審核'), ('reviewing', '審核中'), ('approved', '已批准'), ('rejected', '已拒絕'), ('requires_more_info', '需要更多信息'), ('cancelled', '已取消'), ('on_hold', '暫停'), ('re_review', '重新審核'), ('auto_approved', '自動批准'), ('expired', '已過期')], default='pending', max_length=20, verbose_name='審核狀態'),
        ),
        migrations.AlterField(
            model_name='enrollmentnumbers',
            name='status',
            field=models.CharField(choices=[('pending', '待審核'), ('reviewing', '審核中'), ('approved', '已批准'), ('rejected', '已拒絕'), ('requires_more_info', '需要更多信息'), ('cancelled', '已取消'), ('on_hold', '暫停'), ('re_review', '重新審核'), ('auto_approved', '自動批准'), ('expired', '已過期')], default='pending', max_length=20, verbose_name='審核狀態'),
        ),
    ]
