# Generated by Django 5.0.4 on 2024-06-06 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_alter_assignedcourse_assigned_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollmentlist',
            name='enrollment_status',
            field=models.CharField(blank=True, choices=[('待付款', '待付款'), ('未開課', '未開課'), ('審核中', '審核中'), ('派課中', '派課中'), ('已派課', '已派課'), ('進行中', '進行中'), ('已完成', '已完成'), ('已取消', '已取消'), ('已退款', '已退款'), ('已停課', '已停課')], default='待付款', max_length=20, null=True, verbose_name='報名狀態'),
        ),
    ]
