# Generated by Django 5.0.4 on 2024-06-06 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_alter_enrollmentlist_enrollment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursetype',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='課程類型名稱'),
        ),
    ]
