# Generated by Django 5.0.4 on 2024-06-07 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_alter_coursetype_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='enrollment_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='courses.enrollmentlist', verbose_name='報名表'),
        ),
        migrations.AlterField(
            model_name='enrollmentlist',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('現金', '現金')], default='cash', max_length=20, null=True, verbose_name='付款方式'),
        ),
    ]
