# Generated by Django 5.0.4 on 2024-06-09 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_alter_assignedcourse_status_alter_course_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_status',
            field=models.CharField(blank=True, choices=[('未開課', '未開課'), ('進行中', '進行中'), ('已取消', '已取消'), ('已完成', '已完成'), ('已停課', '已停課')], default='進行中', max_length=20, null=True, verbose_name='課程狀態'),
        ),
    ]
