# Generated by Django 5.0.4 on 2024-06-10 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_alter_course_course_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmentlist',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='年齡'),
        ),
    ]
