# Generated by Django 5.0.4 on 2024-06-16 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_alter_enrollmentlist_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollmentlist',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('現金', '現金')], max_length=20, null=True, verbose_name='付款方式'),
        ),
    ]
