# Generated by Django 5.0.4 on 2024-06-18 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_alter_enrollmentlist_enrollment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedcourse',
            name='assigned_status',
            field=models.CharField(choices=[('待決定', '待決定'), ('已接受', '已接受'), ('已拒絕', '已拒絕')], default='待決定', max_length=20, verbose_name='狀態'),
        ),
    ]
