# Generated by Django 5.0.4 on 2024-06-18 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0024_alter_assignedcourse_assigned_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollmentnumbers',
            name='enrollments',
        ),
    ]
