# Generated by Django 5.0.4 on 2024-06-20 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0026_alter_enrollmentnumbers_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollmentlist',
            name='payment_amount',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='付款金額'),
        ),
    ]
