# Generated by Django 5.0.4 on 2024-06-24 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0027_alter_enrollmentlist_payment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursetype',
            name='limit',
            field=models.IntegerField(blank=True, null=True, verbose_name='人數限制'),
        ),
    ]
