# Generated by Django 5.0.4 on 2024-05-26 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewstage',
            options={'ordering': ['order'], 'verbose_name': '審核階段', 'verbose_name_plural': '審核階段'},
        ),
        migrations.AlterModelTable(
            name='reviewstage',
            table='review_stages',
        ),
    ]
