# Generated by Django 5.0.4 on 2024-05-26 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('humanresources', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coach',
            options={'verbose_name': '教练清單', 'verbose_name_plural': '教练清單'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': '员工清單', 'verbose_name_plural': '员工清單'},
        ),
        migrations.AlterModelOptions(
            name='lifeguard',
            options={'verbose_name': '救生员清單', 'verbose_name_plural': '救生员清單'},
        ),
        migrations.AlterModelOptions(
            name='venuemanager',
            options={'verbose_name': '场地管理人员清單', 'verbose_name_plural': '场地管理人员清單'},
        ),
    ]
