# Generated by Django 5.0.4 on 2024-05-18 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('humanresources', '0001_initial'),
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待審核'), ('reviewing', '審核中'), ('approved', '已批准'), ('rejected', '已拒絕'), ('requires_more_info', '需要更多信息'), ('cancelled', '已取消'), ('on_hold', '暫停'), ('re_review', '重新審核'), ('auto_approved', '自動批准'), ('expired', '已過期')], default='pending', max_length=20)),
                ('name', models.CharField(max_length=255, verbose_name='名称')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '授課地点',
                'verbose_name_plural': '授課地点',
                'db_table': 'location',
            },
        ),
        migrations.CreateModel(
            name='ScheduleSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
            options={
                'verbose_name': '排班时间段',
                'verbose_name_plural': '排班时间段',
                'db_table': 'schedule_slot',
            },
        ),
        migrations.CreateModel(
            name='LifeguardSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待審核'), ('reviewing', '審核中'), ('approved', '已批准'), ('rejected', '已拒絕'), ('requires_more_info', '需要更多信息'), ('cancelled', '已取消'), ('on_hold', '暫停'), ('re_review', '重新審核'), ('auto_approved', '自動批准'), ('expired', '已過期')], default='pending', max_length=20)),
                ('date', models.DateField(default=None, verbose_name='日期')),
                ('start_time', models.TimeField(default=None, verbose_name='开始时间')),
                ('end_time', models.TimeField(default=None, verbose_name='结束时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('lifeguard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lifeguard_schedules', to='humanresources.lifeguard', verbose_name='救生员')),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lifeguard_schedules', to='venues.venue', verbose_name='地点')),
            ],
            options={
                'verbose_name': '救生员月排班表',
                'verbose_name_plural': '救生员月排班表',
                'db_table': 'lifeguard_schedule',
                'unique_together': {('lifeguard', 'venue', 'date', 'start_time', 'end_time')},
            },
        ),
        migrations.CreateModel(
            name='CoachAvailableSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待審核'), ('reviewing', '審核中'), ('approved', '已批准'), ('rejected', '已拒絕'), ('requires_more_info', '需要更多信息'), ('cancelled', '已取消'), ('on_hold', '暫停'), ('re_review', '重新審核'), ('auto_approved', '自動批准'), ('expired', '已過期')], default='pending', max_length=20)),
                ('day_of_week', models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], default=1, verbose_name='星期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_schedules', to='humanresources.coach', verbose_name='教练')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coach_schedules', to='schedule.location', verbose_name='地点')),
                ('schedule_slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coach_schedules', to='schedule.scheduleslot', verbose_name='时间段')),
            ],
            options={
                'verbose_name': '教练可上班週排表',
                'verbose_name_plural': '教练可上班週排表',
                'db_table': 'coach_available_slot',
                'unique_together': {('coach', 'day_of_week', 'schedule_slot', 'location')},
            },
        ),
        migrations.CreateModel(
            name='UnavailableSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待審核'), ('reviewing', '審核中'), ('approved', '已批准'), ('rejected', '已拒絕'), ('requires_more_info', '需要更多信息'), ('cancelled', '已取消'), ('on_hold', '暫停'), ('re_review', '重新審核'), ('auto_approved', '自動批准'), ('expired', '已過期')], default='pending', max_length=20)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('allow', models.BooleanField(default=None)),
                ('lifeguard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='humanresources.lifeguard')),
            ],
            options={
                'unique_together': {('lifeguard', 'date', 'start_time', 'end_time')},
            },
        ),
    ]
