# Generated by Django 5.0.4 on 2024-05-26 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unavailableslot',
            options={'verbose_name': '救生员排假表', 'verbose_name_plural': '救生员排假表'},
        ),
        migrations.AlterModelTable(
            name='unavailableslot',
            table='unavailable_slot',
        ),
    ]
