# Generated by Django 5.0.4 on 2024-05-26 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_alter_unavailableslot_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': '教练授課地点', 'verbose_name_plural': '教练授課地点'},
        ),
        migrations.AlterModelOptions(
            name='scheduleslot',
            options={'verbose_name': '教练排班时间段', 'verbose_name_plural': '教练排班时间段'},
        ),
    ]
