# Generated by Django 5.0.4 on 2024-06-14 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humanresources', '0005_alter_coach_status_alter_employee_status_and_more'),
        ('schedule', '0006_alter_coachavailableslot_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoahcSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('週一', '週一'), ('週二', '週二'), ('週三', '週三'), ('週四', '週四'), ('週五', '週五'), ('週六', '週六'), ('週日', '週日')], max_length=10)),
                ('time_slot', models.CharField(max_length=20)),
                ('is_available', models.BooleanField(default=False)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='humanresources.coach')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='schedule.location')),
            ],
            options={
                'verbose_name': '教練排班',
                'verbose_name_plural': '教練排班',
                'unique_together': {('coach', 'location', 'day_of_week', 'time_slot')},
            },
        ),
    ]
