# Generated by Django 5.0.4 on 2024-06-14 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_coahcschedule'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CoachAvailableSlot',
        ),
        migrations.DeleteModel(
            name='ScheduleSlot',
        ),
    ]
