# Generated by Django 5.0.4 on 2024-06-15 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0008_delete_coachavailableslot_delete_scheduleslot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lifeguardschedule',
            name='status',
            field=models.CharField(choices=[('待審核', '待審核'), ('審核中', '審核中'), ('已批准', '已批准'), ('已拒絕', '已拒絕'), ('需要更多信息', '需要更多信息'), ('已取消', '已取消'), ('暫停', '暫停'), ('重新審核', '重新審核'), ('自動批准', '自動批准'), ('已過期', '已過期')], default='待審核', max_length=20, verbose_name='審核狀態'),
        ),
        migrations.AlterField(
            model_name='location',
            name='status',
            field=models.CharField(choices=[('待審核', '待審核'), ('審核中', '審核中'), ('已批准', '已批准'), ('已拒絕', '已拒絕'), ('需要更多信息', '需要更多信息'), ('已取消', '已取消'), ('暫停', '暫停'), ('重新審核', '重新審核'), ('自動批准', '自動批准'), ('已過期', '已過期')], default='待審核', max_length=20, verbose_name='審核狀態'),
        ),
        migrations.AlterField(
            model_name='unavailableslot',
            name='end_time',
            field=models.TimeField(default='22:00'),
        ),
        migrations.AlterField(
            model_name='unavailableslot',
            name='start_time',
            field=models.TimeField(default='07:00'),
        ),
        migrations.AlterField(
            model_name='unavailableslot',
            name='status',
            field=models.CharField(choices=[('待審核', '待審核'), ('審核中', '審核中'), ('已批准', '已批准'), ('已拒絕', '已拒絕'), ('需要更多信息', '需要更多信息'), ('已取消', '已取消'), ('暫停', '暫停'), ('重新審核', '重新審核'), ('自動批准', '自動批准'), ('已過期', '已過期')], default='待審核', max_length=20, verbose_name='審核狀態'),
        ),
    ]
