# Generated by Django 5.0.4 on 2024-06-07 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_alter_attendance_attend_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='attend_status',
            field=models.CharField(blank=True, choices=[('已簽到', '已簽到'), ('已補簽', '已補簽'), ('管理者補簽', '管理者補簽'), ('未通過驗證', '未通過驗證'), ('未簽到', '未簽到')], max_length=20, null=True, verbose_name='簽到狀態'),
        ),
        migrations.AlterField(
            model_name='lifeguardattendance',
            name='attend_status',
            field=models.CharField(blank=True, choices=[('已簽到', '已簽到'), ('已補簽', '已補簽'), ('管理者補簽', '管理者補簽'), ('未簽到', '未簽到'), ('已簽退', '已簽退'), ('補簽退', '補簽退'), ('管理者補簽退', '管理者補簽退'), ('未簽退', '未簽退'), ('未通過驗證', '未通過驗證')], max_length=50, null=True, verbose_name='簽到狀態'),
        ),
        migrations.AlterField(
            model_name='staffattendance',
            name='attend_status',
            field=models.CharField(blank=True, choices=[('已簽到', '已簽到'), ('已補簽', '已補簽'), ('管理者補簽', '管理者補簽'), ('未簽到', '未簽到'), ('已簽退', '已簽退'), ('補簽退', '補簽退'), ('管理者補簽退', '管理者補簽退'), ('未簽退', '未簽退'), ('未通過驗證', '未通過驗證')], max_length=50, null=True, verbose_name='簽到狀態'),
        ),
    ]
