# Generated by Django 5.0.4 on 2024-06-09 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_alter_attendance_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='attend_status',
            field=models.CharField(blank=True, choices=[('簽到', '簽到'), ('補簽', '補簽'), ('未簽到', '未簽到')], max_length=20, null=True, verbose_name='簽到狀態'),
        ),
        migrations.AlterField(
            model_name='lifeguardattendance',
            name='attend_status',
            field=models.CharField(blank=True, choices=[('簽到', '簽到'), ('補簽', '補簽'), ('未簽到', '未簽到'), ('簽退', '簽退'), ('補簽退', '補簽退'), ('未簽退', '未簽退'), ('未通過驗證', '未通過驗證')], max_length=50, null=True, verbose_name='簽到狀態'),
        ),
    ]
