# Generated by Django 5.0.4 on 2024-05-26 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyze', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useractivity',
            options={'verbose_name': '使用者活動', 'verbose_name_plural': '使用者活動'},
        ),
        migrations.AlterModelTable(
            name='useractivity',
            table='user_activity',
        ),
    ]
