# Generated by Django 5.0.8 on 2024-08-16 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_alter_notification_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='groups',
        ),
        migrations.AddField(
            model_name='notification',
            name='read_status',
            field=models.BooleanField(default=False, verbose_name='已讀'),
        ),
        migrations.AlterField(
            model_name='notificationtype',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='類別名稱'),
        ),
    ]
