# Generated by Django 5.0.8 on 2024-08-16 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_remove_notification_groups_notification_read_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationmethod',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='推送方式'),
        ),
    ]
