# Generated by Django 5.0.8 on 2024-08-17 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_alter_notificationmethod_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='method',
            field=models.CharField(blank=True, choices=[('LINE', 'LINE'), ('MESSENGER', 'MESSENGER'), ('EMAIL', 'EMAIL'), ('SMS', 'SMS'), ('APP', 'APP')], max_length=20, null=True, verbose_name='推送方式'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('全體公告', '全體公告')], max_length=50, verbose_name='類別'),
        ),
        migrations.DeleteModel(
            name='NotificationMethod',
        ),
        migrations.DeleteModel(
            name='NotificationType',
        ),
    ]
