# Generated by Django 5.0.4 on 2024-05-26 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Banner橫幅', 'verbose_name_plural': 'Banner橫幅'},
        ),
        migrations.AlterModelTable(
            name='banner',
            table='banner',
        ),
    ]
