from .permissions import *

VIEWSET_PERMISSIONS = {
    'AttendanceViewSet': {
        'create': [IsManagerGroup(), IsAdministratorGroup(), IsStaffGroup(), IsLifeguardGroup(), IsStudentGroup(), IsCoachGroup()],
        'list': [IsManagerGroup(), IsAdministratorGroup(), IsStaffGroup(), IsLifeguardGroup()],
        'retrieve': [IsManagerGroup(), IsAdministratorGroup()],
        'update': [IsManagerGroup(), IsAdministratorGroup(), IsStaffGroup(), IsLifeguardGroup()],
        'destroy': [IsManagerGroup(), IsAdministratorGroup(), IsStaffGroup()],
    },
    'LifeguardAttendanceViewSet': {
        'create': [IsLifeguardGroup()],
        'list': [IsManagerGroup(), IsAdministratorGroup(), IsLifeguardGroup()],
        'retrieve': [IsManagerGroup(), IsAdministratorGroup(), IsLifeguardGroup()],
        'update': [IsLifeguardGroup()],
        'destroy': [IsLifeguardGroup()],
    },
    'StaffAttendanceViewSet': {
        'create': [IsStaffGroup()],
        'list': [IsManagerGroup(), IsAdministratorGroup(), IsStaffGroup()],
        'retrieve': [IsManagerGroup(), IsAdministratorGroup(), IsStaffGroup()],
        'update': [IsStaffGroup()],
        'destroy': [IsStaffGroup()],
    },
    'CourseViewSet': {
        'create': [IsManagerGroup(), IsAdministratorGroup()],
        'list': [IsManagerGroup(), IsAdministratorGroup(), IsStaffGroup(), IsLifeguardGroup(), IsStudentGroup(), IsCoachGroup()],
        'retrieve': [IsManagerGroup(), IsAdministratorGroup(), IsStaffGroup(), IsLifeguardGroup(), IsStudentGroup(), IsCoachGroup()],
        'update': [IsManagerGroup(), IsAdministratorGroup()],
        'destroy': [IsManagerGroup(), IsAdministratorGroup()],
    },
    'EnrollmentViewSet': {
        'create': [IsManagerGroup(), IsAdministratorGroup()],
        'list': [IsManagerGroup(), IsAdministratorGroup(), IsStaffGroup(), IsLifeguardGroup(), IsStudentGroup(), IsCoachGroup()],
        'retrieve': [IsManagerGroup(), IsAdministratorGroup(), IsStaffGroup(), IsLifeguardGroup(), IsStudentGroup(), IsCoachGroup()],
        'update': [IsManagerGroup(), IsAdministratorGroup()],
        'destroy': [IsManagerGroup(), IsAdministratorGroup()],
    },
    'AssignedCourseViewSet': {
        'create': [IsManagerGroup(), IsAdministratorGroup()],
        'list': [IsManagerGroup(), IsAdministratorGroup(), IsStaffGroup(), IsLifeguardGroup(), IsStudentGroup(), IsCoachGroup()],
        'retrieve': [IsManagerGroup(), IsAdministratorGroup(), IsStaffGroup(), IsLifeguardGroup(), IsStudentGroup(), IsCoachGroup()],
        'update': [IsManagerGroup(), IsAdministratorGroup()],
        'destroy': [IsManagerGroup(), IsAdministratorGroup()],
    },
    'CourseTypeViewSet': {
        'create': [IsManagerGroup(), IsAdministratorGroup()],
        'list': [IsManagerGroup(), IsAdministratorGroup(), IsStaffGroup(), IsLifeguardGroup(), IsStudentGroup(), IsCoachGroup()],
        'retrieve': [IsManagerGroup(), IsAdministratorGroup(), IsStaffGroup(), IsLifeguardGroup(), IsStudentGroup(), IsCoachGroup()],
        'update': [IsManagerGroup(), IsAdministratorGroup()],
        'destroy': [IsManagerGroup(), IsAdministratorGroup()],
    },
    'CoachViewSet': {
        'create': [IsManagerGroup(), IsAdministratorGroup()],
        'list': [IsManagerGroup(), IsAdministratorGroup(), IsStaffGroup(), IsLifeguardGroup(), IsStudentGroup(), IsCoachGroup()],
        'retrieve': [IsManagerGroup(), IsAdministratorGroup(), IsStaffGroup(), IsLifeguardGroup(), IsStudentGroup(), IsCoachGroup()],
        'update': [IsManagerGroup(), IsAdministratorGroup()],
        'destroy': [IsManagerGroup(), IsAdministratorGroup()],
    },
    'LifeguardViewSet': {
        'create': [IsManagerGroup(), IsAdministratorGroup()],
        'list': [IsManagerGroup(), IsAdministratorGroup(), IsStaffGroup(), IsLifeguardGroup(), IsStudentGroup(), IsCoachGroup()],
        'retrieve': [IsManagerGroup(), IsAdministratorGroup(), IsStaffGroup(), IsLifeguardGroup(), IsStudentGroup(), IsCoachGroup()],
        'update': [IsManagerGroup(), IsAdministratorGroup()],
        'destroy': [IsManagerGroup(), IsAdministratorGroup()],
    },
    'PerformanceViewSet': {
        'create': [IsManagerGroup(), IsAdministratorGroup()],
        'list': [IsManagerGroup(), IsAdministratorGroup(), IsStaffGroup(), IsLifeguardGroup(), IsStudentGroup(), IsCoachGroup()],
        'retrieve': [IsManagerGroup(), IsAdministratorGroup(), IsStaffGroup(), IsLifeguardGroup(), IsStudentGroup(), IsCoachGroup()],
        'update': [IsManagerGroup(), IsAdministratorGroup()],
        'destroy': [IsManagerGroup(), IsAdministratorGroup()],
    },
    'SalaryViewSet': {
        'create': [IsManagerGroup(), IsAdministratorGroup()],
        'list': [IsManagerGroup(), IsAdministratorGroup(), IsStaffGroup(), IsLifeguardGroup(), IsStudentGroup(), IsCoachGroup()],
        'retrieve': [IsManagerGroup(), IsAdministratorGroup(), IsStaffGroup(), IsLifeguardGroup(), IsStudentGroup(), IsCoachGroup()],
        'update': [IsManagerGroup(), IsAdministratorGroup()],
        'destroy': [IsManagerGroup(), IsAdministratorGroup()],
    },
    'EmployeeViewSet': {
        'create': [IsManagerGroup(), IsAdministratorGroup()],
        'list': [IsManagerGroup(), IsAdministratorGroup(), IsStaffGroup(), IsLifeguardGroup(), IsStudentGroup(), IsCoachGroup()],
        'retrieve': [IsManagerGroup(), IsAdministratorGroup(), IsStaffGroup(), IsLifeguardGroup(), IsStudentGroup(), IsCoachGroup()],
        'update': [IsManagerGroup(), IsAdministratorGroup()],
        'destroy': [IsManagerGroup(), IsAdministratorGroup()],
    },
    'NotificationViewSet': {
        'create': [IsManagerGroup(), IsAdministratorGroup(), IsStaffGroup(), IsLifeguardGroup(), IsStudentGroup(), IsCoachGroup()],
        'list': [IsManagerGroup(), IsAdministratorGroup(), IsStaffGroup(), IsLifeguardGroup()],
        'retrieve': [IsManagerGroup(), IsAdministratorGroup()],
        'update': [IsManagerGroup(), IsAdministratorGroup(), IsStaffGroup(), IsLifeguardGroup()],
        'destroy': [IsManagerGroup(), IsAdministratorGroup(), IsStaffGroup()],
    },
    'NotificationTypeViewSet': {
        'create': [IsManagerGroup(), IsAdministratorGroup()],
        'list': [IsManagerGroup(), IsAdministratorGroup(), IsStaffGroup(), IsLifeguardGroup(), IsStudentGroup(), IsCoachGroup()],
        'retrieve': [IsManagerGroup(), IsAdministratorGroup(), IsStaffGroup(), IsLifeguardGroup(), IsStudentGroup(), IsCoachGroup()],
        'update': [IsManagerGroup(), IsAdministratorGroup()],
        'destroy': [IsManagerGroup(), IsAdministratorGroup()],
    },
    'CoachScheduleViewSet': {
        'create': [IsManagerGroup(), IsAdministratorGroup()],
        'list': [IsManagerGroup(), IsAdministratorGroup(), IsStaffGroup(), IsLifeguardGroup(), IsStudentGroup(), IsCoachGroup()],
        'retrieve': [IsManagerGroup(), IsAdministratorGroup(), IsStaffGroup(), IsLifeguardGroup(), IsStudentGroup(), IsCoachGroup()],
        'update': [IsManagerGroup(), IsAdministratorGroup()],
        'destroy': [IsManagerGroup(), IsAdministratorGroup()],
    },
    'LifeguardScheduleViewSet': {
        'create': [IsManagerGroup(), IsAdministratorGroup()],
        'list': [IsManagerGroup(), IsAdministratorGroup(), IsStaffGroup(), IsLifeguardGroup(), IsStudentGroup(), IsCoachGroup()],
        'retrieve': [IsManagerGroup(), IsAdministratorGroup(), IsStaffGroup(), IsLifeguardGroup(), IsStudentGroup(), IsCoachGroup()],
        'update': [IsManagerGroup(), IsAdministratorGroup()],
        'destroy': [IsManagerGroup(), IsAdministratorGroup()],
    },
    'TweetViewSet': {
        'create': [IsManagerGroup(), IsAdministratorGroup(), IsStaffGroup(), IsLifeguardGroup(), IsStudentGroup(), IsCoachGroup()],
        'list': [IsManagerGroup(), IsAdministratorGroup(), IsStaffGroup(), IsLifeguardGroup()],
        'retrieve': [IsManagerGroup(), IsAdministratorGroup()],
        'update': [IsManagerGroup(), IsAdministratorGroup(), IsStaffGroup(), IsLifeguardGroup()],
        'destroy': [IsManagerGroup(), IsAdministratorGroup(), IsStaffGroup()],
    },
    'TweetLikeViewSet': {
        'create': [IsManagerGroup(), IsAdministratorGroup(), IsStaffGroup(), IsLifeguardGroup(), IsStudentGroup(), IsCoachGroup()],
        'list': [IsManagerGroup(), IsAdministratorGroup(), IsStaffGroup(), IsLifeguardGroup()],
        'retrieve': [IsManagerGroup(), IsAdministratorGroup()],
        'update': [IsManagerGroup(), IsAdministratorGroup(), IsStaffGroup(), IsLifeguardGroup()],
        'destroy': [IsManagerGroup(), IsAdministratorGroup(), IsStaffGroup()],
    },
    'TweetCommentViewSet': {
        'create': [IsManagerGroup(), IsAdministratorGroup(), IsStaffGroup(), IsLifeguardGroup(), IsStudentGroup(), IsCoachGroup()],
        'list': [IsManagerGroup(), IsAdministratorGroup(), IsStaffGroup(), IsLifeguardGroup()],
        'retrieve': [IsManagerGroup(), IsAdministratorGroup()],
        'update': [IsManagerGroup(), IsAdministratorGroup(), IsStaffGroup(), IsLifeguardGroup()],
        'destroy': [IsManagerGroup(), IsAdministratorGroup(), IsStaffGroup()],
    },
    'TweetCommentLikeViewSet': {
        'create': [IsManagerGroup(), IsAdministratorGroup(), IsStaffGroup(), IsLifeguardGroup(), IsStudentGroup(), IsCoachGroup()],
        'list': [IsManagerGroup(), IsAdministratorGroup(), IsStaffGroup(), IsLifeguardGroup()],
        'retrieve': [IsManagerGroup(), IsAdministratorGroup()],
        'update': [IsManagerGroup(), IsAdministratorGroup(), IsStaffGroup(), IsLifeguardGroup()],
        'destroy': [IsManagerGroup(), IsAdministratorGroup(), IsStaffGroup()],
    },
    'WorklogViewSet': {
        'create': [IsManagerGroup(), IsAdministratorGroup(), IsStaffGroup(), IsLifeguardGroup(), IsStudentGroup(), IsCoachGroup()],
        'list': [IsManagerGroup(), IsAdministratorGroup(), IsStaffGroup(), IsLifeguardGroup()],
        'retrieve': [IsManagerGroup(), IsAdministratorGroup()],
        'update': [IsManagerGroup(), IsAdministratorGroup(), IsStaffGroup(), IsLifeguardGroup()],
        'destroy': [IsManagerGroup(), IsAdministratorGroup(), IsStaffGroup()],
    },
    'VenueViewSet': {
        'create': [IsManagerGroup(), IsAdministratorGroup()],
        'list': [IsManagerGroup(), IsAdministratorGroup(), IsStaffGroup(), IsLifeguardGroup(), IsStudentGroup(), IsCoachGroup()],
        'retrieve': [IsManagerGroup(), IsAdministratorGroup(), IsStaffGroup(), IsLifeguardGroup(), IsStudentGroup(), IsCoachGroup()],
        'update': [IsManagerGroup(), IsAdministratorGroup()],
        'destroy': [IsManagerGroup(), IsAdministratorGroup()],
    },
    'VenueUsageRecordViewSet': {
        'create': [IsManagerGroup(), IsAdministratorGroup()],
        'list': [IsManagerGroup(), IsAdministratorGroup(), IsStaffGroup(), IsLifeguardGroup(), IsStudentGroup(), IsCoachGroup()],
        'retrieve': [IsManagerGroup(), IsAdministratorGroup(), IsStaffGroup(), IsLifeguardGroup(), IsStudentGroup(), IsCoachGroup()],
        'update': [IsManagerGroup(), IsAdministratorGroup()],
        'destroy': [IsManagerGroup(), IsAdministratorGroup()],
    },
    'VenueBookingViewSet': {
        'create': [IsManagerGroup(), IsAdministratorGroup()],
        'list': [IsManagerGroup(), IsAdministratorGroup(), IsStaffGroup(), IsLifeguardGroup(), IsStudentGroup(), IsCoachGroup()],
        'retrieve': [IsManagerGroup(), IsAdministratorGroup(), IsStaffGroup(), IsLifeguardGroup(), IsStudentGroup(), IsCoachGroup()],
        'update': [IsManagerGroup(), IsAdministratorGroup()],
        'destroy': [IsManagerGroup(), IsAdministratorGroup()],
    },
    'VenueBookingStatusViewSet': {
        'create': [IsManagerGroup(), IsAdministratorGroup()],
        'list': [IsManagerGroup(), IsAdministratorGroup(), IsStaffGroup(), IsLifeguardGroup(), IsStudentGroup(), IsCoachGroup()],
        'retrieve': [IsManagerGroup(), IsAdministratorGroup(), IsStaffGroup(), IsLifeguardGroup(), IsStudentGroup(), IsCoachGroup()],
        'update': [IsManagerGroup(), IsAdministratorGroup()],
        'destroy': [IsManagerGroup(), IsAdministratorGroup()],
    },
    'VenueInspectionRecordViewSet': {
        'create': [IsManagerGroup(), IsAdministratorGroup()],
        'list': [IsManagerGroup(), IsAdministratorGroup(), IsStaffGroup(), IsLifeguardGroup(), IsStudentGroup(), IsCoachGroup()],
        'retrieve': [IsManagerGroup(), IsAdministratorGroup(), IsStaffGroup(), IsLifeguardGroup(), IsStudentGroup(), IsCoachGroup()],
        'update': [IsManagerGroup(), IsAdministratorGroup()],
        'destroy': [IsManagerGroup(), IsAdministratorGroup()],
    },
    'VenueRepairRequestViewSet': {
        'create': [IsManagerGroup(), IsAdministratorGroup()],
        'list': [IsManagerGroup(), IsAdministratorGroup(), IsStaffGroup(), IsLifeguardGroup(), IsStudentGroup(), IsCoachGroup()],
        'retrieve': [IsManagerGroup(), IsAdministratorGroup(), IsStaffGroup(), IsLifeguardGroup(), IsStudentGroup(), IsCoachGroup()],
        'update': [IsManagerGroup(), IsAdministratorGroup()],
        'destroy': [IsManagerGroup(), IsAdministratorGroup()],
    },
    

}